---
Name: Web Crawler
Type: Config

Nodes: # Dictates where node level configurations are stored
  index: github.com/bign8/pipelines/sample/web
  crawl: github.com/bign8/pipelines/sample/web
  store: github.com/bign8/pipelines/sample/web
---
Name: index
Type: Node
CMD: go run sample/web/*.go

In:
  index_request: "@"

Out:
  - crawl_request
---
Name: store
Type: Node
CMD: go run sample/web/*.go

In:
  store_request: "@"
---
Name: crawl
Type: Node
CMD: go run sample/web/*.go

In:
  crawl_request: "*"

Out:
  - index_request
  - store_request
