// Code generated by protoc-gen-go.
// source: pipelines.proto
// DO NOT EDIT!

/*
Package pipelines is a generated protocol buffer package.

It is generated from these files:
	pipelines.proto

It has these top-level messages:
	Emit
	Work
	Record
	Timer
	StartWorker
*/
package pipelines

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Emit struct {
	Record *Record `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
	Stream string  `protobuf:"bytes,2,opt,name=stream" json:"stream,omitempty"`
}

func (m *Emit) Reset()                    { *m = Emit{} }
func (m *Emit) String() string            { return proto.CompactTextString(m) }
func (*Emit) ProtoMessage()               {}
func (*Emit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Emit) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type Work struct {
	Record  *Record `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
	Service string  `protobuf:"bytes,2,opt,name=service" json:"service,omitempty"`
	Key     string  `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
}

func (m *Work) Reset()                    { *m = Work{} }
func (m *Work) String() string            { return proto.CompactTextString(m) }
func (*Work) ProtoMessage()               {}
func (*Work) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Work) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type Record struct {
	CorrelationID uint64 `protobuf:"varint,1,opt,name=correlationID" json:"correlationID,omitempty"`
	Guid          uint64 `protobuf:"varint,2,opt,name=guid" json:"guid,omitempty"`
	Data          string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Timer struct {
	CorrelationID uint64 `protobuf:"varint,1,opt,name=correlationID" json:"correlationID,omitempty"`
	Guid          uint64 `protobuf:"varint,2,opt,name=guid" json:"guid,omitempty"`
	Stamp         uint64 `protobuf:"varint,3,opt,name=stamp" json:"stamp,omitempty"`
}

func (m *Timer) Reset()                    { *m = Timer{} }
func (m *Timer) String() string            { return proto.CompactTextString(m) }
func (*Timer) ProtoMessage()               {}
func (*Timer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type StartWorker struct {
	Service string `protobuf:"bytes,1,opt,name=service" json:"service,omitempty"`
	Key     string `protobuf:"bytes,2,opt,name=key" json:"key,omitempty"`
	Command string `protobuf:"bytes,3,opt,name=command" json:"command,omitempty"`
	Guid    string `protobuf:"bytes,4,opt,name=guid" json:"guid,omitempty"`
}

func (m *StartWorker) Reset()                    { *m = StartWorker{} }
func (m *StartWorker) String() string            { return proto.CompactTextString(m) }
func (*StartWorker) ProtoMessage()               {}
func (*StartWorker) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*Emit)(nil), "pipelines.Emit")
	proto.RegisterType((*Work)(nil), "pipelines.Work")
	proto.RegisterType((*Record)(nil), "pipelines.Record")
	proto.RegisterType((*Timer)(nil), "pipelines.Timer")
	proto.RegisterType((*StartWorker)(nil), "pipelines.StartWorker")
}

var fileDescriptor0 = []byte{
	// 222 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x90, 0xb1, 0x4b, 0xc5, 0x30,
	0x10, 0x87, 0xa9, 0x2f, 0x2f, 0xf2, 0xae, 0x3e, 0x1f, 0x06, 0x84, 0x8e, 0xda, 0xc9, 0xa9, 0x83,
	0x4e, 0xe2, 0xaa, 0x88, 0x8e, 0x2a, 0x38, 0xc7, 0xe6, 0x90, 0xd0, 0xa6, 0x09, 0x97, 0x53, 0xf0,
	0xbf, 0x37, 0x4d, 0xa5, 0x76, 0xec, 0x14, 0x2e, 0x77, 0xdf, 0x97, 0x5f, 0x0e, 0x0e, 0xc1, 0x06,
	0xec, 0xed, 0x80, 0xb1, 0x09, 0xe4, 0xd9, 0xab, 0xdd, 0x7c, 0x51, 0xdf, 0x82, 0x78, 0x70, 0x96,
	0xd5, 0x25, 0x48, 0xc2, 0xd6, 0x93, 0xa9, 0x8a, 0x8b, 0xe2, 0xaa, 0xbc, 0x3e, 0x6b, 0xfe, 0xa1,
	0x97, 0xdc, 0x50, 0xa7, 0x20, 0x23, 0x13, 0x6a, 0x57, 0x1d, 0xa5, 0x91, 0x5d, 0xfd, 0x08, 0xe2,
	0xdd, 0x53, 0xb7, 0x06, 0x3d, 0xc0, 0x71, 0x44, 0xfa, 0xb6, 0x2d, 0x4e, 0xac, 0x2a, 0x61, 0xd3,
	0xe1, 0x4f, 0xb5, 0xc9, 0xa2, 0x3b, 0x90, 0x7f, 0x73, 0xe7, 0xb0, 0x4f, 0x27, 0x61, 0xaf, 0xd9,
	0xfa, 0xe1, 0xe9, 0x3e, 0x1b, 0x85, 0x3a, 0x01, 0xf1, 0xf9, 0x65, 0x4d, 0x66, 0x73, 0x65, 0x34,
	0xeb, 0x19, 0xde, 0xbe, 0x59, 0x87, 0xb4, 0x8e, 0xdd, 0xc3, 0x36, 0xb2, 0x76, 0x21, 0xc3, 0xa2,
	0x7e, 0x86, 0xf2, 0x95, 0x35, 0xf1, 0xf8, 0x8f, 0xa4, 0x58, 0xc4, 0x2c, 0x96, 0x31, 0xa7, 0xcc,
	0xa9, 0xdb, 0x7a, 0xe7, 0xf4, 0x60, 0xa6, 0xa7, 0x67, 0xb5, 0x18, 0xab, 0x0f, 0x99, 0x77, 0x7b,
	0xf3, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x07, 0x3f, 0xdd, 0x58, 0x6e, 0x01, 0x00, 0x00,
}
