// Code generated by protoc-gen-go.
// source: pipelines.proto
// DO NOT EDIT!

/*
Package shared is a generated protocol buffer package.

It is generated from these files:
	pipelines.proto

It has these top-level messages:
	Emit
	Work
	Record
*/
package shared

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Emit struct {
	Record *Record `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
	Stream string  `protobuf:"bytes,2,opt,name=stream" json:"stream,omitempty"`
}

func (m *Emit) Reset()                    { *m = Emit{} }
func (m *Emit) String() string            { return proto.CompactTextString(m) }
func (*Emit) ProtoMessage()               {}
func (*Emit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Emit) GetRecord() *Record {
	if m != nil {
		return m.Record
	}
	return nil
}

type Work struct {
	CorrelationID uint64 `protobuf:"varint,1,opt,name=correlationID" json:"correlationID,omitempty"`
	Guid          uint64 `protobuf:"varint,2,opt,name=guid" json:"guid,omitempty"`
	Data          string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *Work) Reset()                    { *m = Work{} }
func (m *Work) String() string            { return proto.CompactTextString(m) }
func (*Work) ProtoMessage()               {}
func (*Work) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Record struct {
	CorrelationID uint64 `protobuf:"varint,1,opt,name=correlationID" json:"correlationID,omitempty"`
	Guid          uint64 `protobuf:"varint,2,opt,name=guid" json:"guid,omitempty"`
	Data          string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Emit)(nil), "shared.Emit")
	proto.RegisterType((*Work)(nil), "shared.Work")
	proto.RegisterType((*Record)(nil), "shared.Record")
}

var fileDescriptor0 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0xc8, 0x2c, 0x48,
	0xcd, 0xc9, 0xcc, 0x4b, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0xce, 0x48,
	0x2c, 0x4a, 0x4d, 0x51, 0x32, 0xe3, 0x62, 0x71, 0xcd, 0xcd, 0x2c, 0x11, 0x92, 0xe3, 0x62, 0x2b,
	0x4a, 0x4d, 0xce, 0x2f, 0x4a, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0xe2, 0xd3, 0x83, 0x28,
	0xd0, 0x0b, 0x02, 0x8b, 0x0a, 0xf1, 0x71, 0xb1, 0x15, 0x97, 0x14, 0xa5, 0x26, 0xe6, 0x4a, 0x30,
	0x01, 0xe5, 0x39, 0x95, 0x2c, 0xb9, 0x58, 0xc2, 0xf3, 0x8b, 0xb2, 0x85, 0x44, 0xb9, 0x78, 0x81,
	0xf2, 0x45, 0xa9, 0x39, 0x89, 0x25, 0x99, 0xf9, 0x79, 0x9e, 0x2e, 0x60, 0xed, 0x2c, 0x42, 0x3c,
	0x5c, 0x2c, 0xe9, 0xa5, 0x99, 0x29, 0x60, 0xc5, 0x60, 0x5e, 0x4a, 0x62, 0x49, 0xa2, 0x04, 0x33,
	0x58, 0xab, 0x35, 0x17, 0x1b, 0xd4, 0x50, 0xd2, 0x35, 0x27, 0xb1, 0x81, 0x9d, 0x6f, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x5d, 0x6d, 0xee, 0x05, 0xd1, 0x00, 0x00, 0x00,
}
