// Code generated by protoc-gen-go.
// source: pipelines.proto
// DO NOT EDIT!

/*
Package shared is a generated protocol buffer package.

It is generated from these files:
	pipelines.proto

It has these top-level messages:
	Record
	RecordComplete
	RouteRequest
*/
package shared

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Record struct {
	CorrelationID uint64 `protobuf:"varint,1,opt,name=correlationID" json:"correlationID,omitempty"`
	Guid          uint64 `protobuf:"varint,2,opt,name=guid" json:"guid,omitempty"`
	Data          string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Stream        string `protobuf:"bytes,4,opt,name=stream" json:"stream,omitempty"`
	Source        string `protobuf:"bytes,5,opt,name=source" json:"source,omitempty"`
}

func (m *Record) Reset()                    { *m = Record{} }
func (m *Record) String() string            { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()               {}
func (*Record) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RecordComplete struct {
	CorrelationID uint64 `protobuf:"varint,1,opt,name=correlationID" json:"correlationID,omitempty"`
	Guid          uint64 `protobuf:"varint,2,opt,name=guid" json:"guid,omitempty"`
	RecordQuid    uint64 `protobuf:"varint,3,opt,name=record_quid" json:"record_quid,omitempty"`
}

func (m *RecordComplete) Reset()                    { *m = RecordComplete{} }
func (m *RecordComplete) String() string            { return proto.CompactTextString(m) }
func (*RecordComplete) ProtoMessage()               {}
func (*RecordComplete) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RouteRequest struct {
	CorrelationID uint64 `protobuf:"varint,1,opt,name=correlationID" json:"correlationID,omitempty"`
	Guid          uint64 `protobuf:"varint,2,opt,name=guid" json:"guid,omitempty"`
	Key           string `protobuf:"bytes,3,opt,name=key" json:"key,omitempty"`
	Source        string `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
}

func (m *RouteRequest) Reset()                    { *m = RouteRequest{} }
func (m *RouteRequest) String() string            { return proto.CompactTextString(m) }
func (*RouteRequest) ProtoMessage()               {}
func (*RouteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*Record)(nil), "shared.Record")
	proto.RegisterType((*RecordComplete)(nil), "shared.RecordComplete")
	proto.RegisterType((*RouteRequest)(nil), "shared.RouteRequest")
}

var fileDescriptor0 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x90, 0x3d, 0xcb, 0xc2, 0x30,
	0x10, 0xc7, 0xe9, 0xd3, 0x3c, 0x01, 0xaf, 0xb5, 0x42, 0x44, 0xc8, 0x28, 0x9d, 0x9c, 0x5c, 0xfc,
	0x08, 0xba, 0xe8, 0x24, 0x5d, 0x1d, 0x24, 0x36, 0x87, 0x06, 0xdb, 0x26, 0xcd, 0xcb, 0xe0, 0xb7,
	0xb7, 0x2f, 0x28, 0x8e, 0x9d, 0x8e, 0xdf, 0xc1, 0xfd, 0xff, 0x3f, 0x0e, 0x16, 0x46, 0x19, 0xac,
	0x54, 0x83, 0x6e, 0x6b, 0xac, 0xf6, 0x9a, 0x51, 0xf7, 0x10, 0x16, 0x65, 0x7e, 0x01, 0x5a, 0x60,
	0xa9, 0xad, 0x64, 0x2b, 0x98, 0x77, 0xd3, 0x62, 0x25, 0xbc, 0xd2, 0xcd, 0xf1, 0xc0, 0xa3, 0x75,
	0xb4, 0x21, 0x2c, 0x05, 0x72, 0x0f, 0x4a, 0xf2, 0xbf, 0x0f, 0x49, 0xe1, 0x05, 0x8f, 0x3b, 0x9a,
	0xb1, 0x0c, 0xa8, 0xf3, 0x16, 0x45, 0xcd, 0xc9, 0x97, 0x75, 0xb0, 0x25, 0xf2, 0xff, 0x9e, 0xf3,
	0x13, 0x64, 0x63, 0xf8, 0x5e, 0xd7, 0xa6, 0x42, 0x8f, 0xd3, 0x4a, 0x96, 0x90, 0xd8, 0xe1, 0xec,
	0xda, 0xf6, 0xcb, 0xbe, 0x8b, 0xe4, 0x67, 0x48, 0x0b, 0x1d, 0x3c, 0x16, 0xd8, 0x06, 0x74, 0x7e,
	0x5a, 0x52, 0x02, 0xf1, 0x13, 0x5f, 0x3f, 0xb6, 0xa3, 0xdd, 0x60, 0x7b, 0xa3, 0xc3, 0x27, 0x76,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x86, 0x50, 0x26, 0x75, 0x1c, 0x01, 0x00, 0x00,
}
